import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const root = process.cwd();
const sourceDir = path.join(root, 'public', 'experiments', 'music-graph-study');
const outputDir = path.join(root, 'public', 'downloads');
const outputPath = path.join(outputDir, 'music-graph-study.html');

const [htmlSource, css, questionData, app] = await Promise.all([
  readFile(path.join(sourceDir, 'music_graph_study_lab_complete_fixed.html'), 'utf8'),
  readFile(path.join(sourceDir, 'study.css'), 'utf8'),
  readFile(path.join(sourceDir, 'study-data.js'), 'utf8'),
  readFile(path.join(sourceDir, 'study.js'), 'utf8'),
]);

const requiredMarkers = [
  '<link rel="stylesheet" href="./study.css">',
  '<script src="./study-data.js"></script>',
  '<script src="./study.js"></script>',
];

for (const marker of requiredMarkers) {
  if (!htmlSource.includes(marker)) throw new Error(`Offline build marker not found: ${marker}`);
}

const safeScript = (source) => source.replaceAll('</script>', '<\\/script>');
const themeBootstrap = `<script>(()=>{const key='erich-lab-theme';let theme='dark';try{theme=localStorage.getItem(key)==='light'?'light':'dark'}catch{}document.documentElement.dataset.theme=theme;})();</script>`;
const offlineCss = `<style>
.offline-toolbar{position:sticky;top:0;z-index:20;display:flex;justify-content:space-between;align-items:center;gap:12px;padding:8px 14px;border-bottom:1px solid var(--l);background:color-mix(in srgb,var(--bg) 92%,transparent);backdrop-filter:blur(14px);font-size:.82rem;color:var(--m)}
.offline-toolbar button{border:1px solid var(--l);border-radius:8px;padding:6px 10px;background:var(--ctl);color:var(--i);cursor:pointer}
@media print{.offline-toolbar{display:none}}
</style>`;
const offlineBar = `<div class="offline-toolbar"><span>Offline copy · Music-Credit Graph Study Lab</span><button type="button" data-offline-theme>Toggle theme</button></div>`;
const themeToggle = `<script>(()=>{const key='erich-lab-theme';const button=document.querySelector('[data-offline-theme]');button?.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=next;try{localStorage.setItem(key,next)}catch{}});})();</script>`;

let output = htmlSource
  .replace(
    '<link rel="stylesheet" href="./study.css">',
    `<meta name="description" content="A self-contained offline copy of the Music-Credit Graph Study Lab.">${themeBootstrap}<style>${css}</style>${offlineCss}`,
  )
  .replace('<body>', `<body>${offlineBar}`)
  .replace('<script src="./study-data.js"></script>', `<script>${safeScript(questionData)}</script>`)
  .replace('<script src="./study.js"></script>', `<script>${safeScript(app)}</script>${themeToggle}`);

output = `<!-- Generated by scripts/build-offline.mjs. Edit the source experiment files instead. -->\n${output}`;

await mkdir(outputDir, { recursive: true });
await writeFile(outputPath, output, 'utf8');
console.log(`✓ Built ${path.relative(root, outputPath)}`);
